spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db001.dev:3306/test
    username: root
    password: 654321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



#端口,默认8080
server:
  port: 8088

#可以理解为访问路径
#server.context-path=/demo

#读取配置文件属性
name: zml
age:  28

#属性引用属性
context: name is ${name} , age is ${age}

app:
  name: zhangsan
  age:  18



##启动方式，指定环境
 #java -jar demo-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev